version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8550:8550"
    environment:
      - FLET_PORT=8550
      - FLET_VIEW=web
    volumes:
      - ./data:/app/data
    restart: unless-stopped
